Repository zauberzeug/field_friend, pull requests merged in 2024-10, with the labels that each got.

#188 Use GNSS RTK in simulation
  field_friend/localization/gnss_simulation.py
  tests/test_navigation.py
Labels: enhancement

#193 Update Rosys to v0.17.1
  requirements.txt
Labels: enhancement

#180 Field Navigation
  field_friend/automations/__init__.py
  field_friend/automations/automation_watcher.py
  field_friend/automations/field.py
  field_friend/automations/field_provider.py
  field_friend/automations/navigation/__init__.py
  field_friend/automations/navigation/a_b_line_navigation.py
  field_friend/automations/navigation/coverage_navigation.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/row_on_field_navigation.py
  field_friend/automations/navigation/todo_ui.py
  field_friend/interface/components/field_object.py
  field_friend/interface/components/robot_scene.py
  field_friend/interface/pages/main_page.py
  field_friend/system.py
  tests/conftest.py
  tests/test_field_creator.py
  tests/test_navigation.py
Labels: enhancement

#194 BMS Page with BMS History
  field_friend/hardware/__init__.py
  field_friend/hardware/bms_status.py
  field_friend/interface/pages/__init__.py
  field_friend/interface/pages/bms_page.py
  field_friend/log_configuration.py
  field_friend/system.py
  main.py
Labels: enhancement

#190 add Automation time tracking
  field_friend/automations/implements/chop_and_screw.py
  field_friend/automations/implements/implement.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/kpi_provider.py
  field_friend/automations/navigation/crossglide_demo_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/puncher.py
  field_friend/interface/components/status_drawer.py
  field_friend/system.py
Labels: enhancement

#199 Change log of camera
  field_friend/vision/calibratable_usb_camera_provider.py
  field_friend/vision/zedxmini_camera/zedxmini_camera_provider.py
Labels: enhancement

#202 Update to Rosys version 0.18.2
  field_friend/interface/components/development.py
  field_friend/interface/components/field_creator.py
  field_friend/interface/components/monitoring.py
  field_friend/vision/camera_configurator.py
  field_friend/vision/zedxmini_camera/zedxmini_camera.py
  field_friend/vision/zedxmini_camera/zedxmini_camera_provider.py
  requirements.txt
Labels: enhancement

#206 Use pip-cache for github tests
  .github/workflows/test.yml
Labels: enhancement

#200 Support Points for Specific Rows
  field_friend/automations/__init__.py
  field_friend/automations/field.py
  field_friend/automations/field_provider.py
  field_friend/interface/components/__init__.py
  field_friend/interface/components/operation.py
  field_friend/interface/components/support_point_dialog.py
  tests/conftest.py
  tests/old_field_provider_persistence.json
  tests/test_field_creator.py
  tests/test_field_provider.py
  tests/test_navigation.py
Labels: enhancement

#189 Remove the need for gnss pausing
  field_friend/automations/automation_watcher.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/interface/components/status_dev.py
  field_friend/localization/gnss.py
  field_friend/localization/gnss_simulation.py
  tests/test_gnss.py
  tests/test_navigation.py
Labels: enhancement

#207 Rework turning after row
  field_friend/automations/navigation/field_navigation.py
Labels: enhancement

#210 Teltonika Status Fix
  field_friend/hardware/teltonika_router.py
Labels: bug

#208 KPI Time Logging Fix
  field_friend/automations/automation_watcher.py
  field_friend/automations/navigation/navigation.py
Labels: bug

#211 Add Field Navigation Developer UI to the dev page
  field_friend/automations/navigation/field_navigation.py
  field_friend/interface/components/development.py
Labels: enhancement

#212 Teltonika Connection Error Handling
  field_friend/hardware/teltonika_router.py
Labels: enhancement

#216 Deactivate GNSS watcher in field navigation
  field_friend/automations/navigation/field_navigation.py
Labels: enhancement

#214 Drive in small steps to next row
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
Labels: enhancement

#217 Rosys 0.18.6
  requirements.txt
Labels: enhancement

#218 FieldNavigation Improvements
  field_friend/automations/navigation/field_navigation.py
Labels: bug, enhancement
