Repository zauberzeug/field_friend, pull requests merged in 2024-07, with the labels that each got.

#99 Add thymian as category
  field_friend/system.py
Labels: enhancement

#101 Only draw plants in 3d if they are above the threshold
  field_friend/interface/components/plant_object.py
Labels: enhancement

#98 Stick to latest RoSys release (0.10.10)
  sync.py
Labels: enhancement

#104 Add 'autoupload' to detector tags
  field_friend/automations/plant_locator.py
Labels: enhancement

#97 Do not show rosys debug logs
  field_friend/log_configuration.py
Labels: enhancement

#93 Deactivate image upload of detector
  docker-compose.jetson.orin.yml
  field_friend/automations/plant_locator.py
Labels: enhancement

#106 Change set_outbox_mode log to debug
  field_friend/automations/plant_locator.py
Labels: enhancement

#107 Request backup on settings change for plant_provider
  field_friend/automations/plant_provider.py
Labels: enhancement

#90 Add PunchDialog option for all weeding implements
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/kpi_provider.py
  field_friend/automations/puncher.py
  field_friend/interface/components/operation.py
  field_friend/interface/components/punch_dialog.py
Labels: enhancement

#110 Run tests as continuous integration with GitHub Action
  .github/workflows/test.yml
  field_friend/__init__.py
  tests/test_gnss.py
  tests/test_navigation.py
Labels: enhancement

#115 Fix punch dialog for the refactorings which have been done on #102
  field_friend/automations/implements/implement.py
  field_friend/automations/implements/punch_dialog.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/puncher.py
  field_friend/interface/components/operation.py
Labels: enhancement

#102 Fix selecting weeds which need to be removed
  field_friend/automations/implements/implement.py
  field_friend/automations/implements/punch_dialog.py
  field_friend/automations/implements/recorder.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/coverage_navigation.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/row_on_field_navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/automations/plant_provider.py
  field_friend/automations/puncher.py
  field_friend/interface/components/camera_card.py
  field_friend/interface/components/operation.py
  field_friend/interface/pages/main_page.py
  field_friend/system.py
  tests/test_navigation.py
  tests/test_weeding.py
Labels: bug, enhancement

#116 Add milestone_check action
  .github/workflows/milestone_check.yml
Labels: enhancement

#118 Update detector to 0.1.1-nlv0.10.9-35.4.1
  docker-compose.jetson.orin.yml
Labels: enhancement

#120 Log battery infos
  field_friend/system.py
Labels: enhancement

#121 Fix compatibility with latest rosys
  field_friend/vision/simulated_cam_provider.py
Labels: enhancement

#117 Precise stopping
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/hardware/field_friend_simulation.py
  field_friend/localization/gnss_simulation.py
  field_friend/system.py
  tests/test_field_provider.py
  tests/test_gnss.py
  tests/test_navigation.py
Labels: enhancement

#124 Add test to ensure we can navigate even though the GNSS location becomes None
  tests/test_navigation.py
Labels: enhancement

#134 Fix yaw computation
  field_friend/automations/navigation/navigation.py
Labels: enhancement

#129 Remove individual field references in favour of a simplified "global" reference for all coordinates
  field_friend/automations/field.py
  field_friend/automations/field_provider.py
  field_friend/automations/navigation/coverage_navigation.py
  field_friend/automations/navigation/row_on_field_navigation.py
  field_friend/automations/path_provider.py
  field_friend/automations/path_recorder.py
  field_friend/interface/components/field_creator.py
  field_friend/interface/components/field_object.py
  field_friend/interface/components/field_planner.py
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/components/status_dev.py
  field_friend/interface/components/status_drawer.py
  field_friend/localization/__init__.py
  field_friend/localization/geo_point.py
  field_friend/localization/gnss.py
  field_friend/localization/gnss_simulation.py
  field_friend/system.py
  tests/conftest.py
  tests/test_field_creator.py
  tests/test_field_provider.py
  tests/test_gnss.py
  tests/test_navigation.py
Labels: enhancement

#112 i/o page
  config/u4_config_rb28/hardware.py
  field_friend/hardware/__init__.py
  field_friend/interface/components/__init__.py
  field_friend/interface/components/development.py
  field_friend/interface/components/header_bar.py
  field_friend/interface/components/io_overview.py
  field_friend/interface/components/status_bulb.py
  field_friend/interface/pages/dev_page.py
Labels: enhancement

#138 Refactor confidences
  field_friend/automations/plant_locator.py
  field_friend/automations/plant_provider.py
  tests/test_plant_provider.py
Labels: enhancement

#141 Remove obsolete configuration files
  config/ff10XL_config_rb30/config_rb30.py
  config/ff11_config_rb31/config_rb31.py
  config/ff3_config_rb26/config_rb26.py
  config/u1_config_z34/config_z34.py
  config/u2_config_rb25/config_rb25.py
  config/u3_config_rb27/config_rb27.py
  config/u4_config_rb28/config_rb28.py
Labels: enhancement

#145 use RoSys 0.12.0 and improve sync.py
  requirements.txt
  sync.py
Labels: enhancement

#144 Disable untested tornado features in UI
  field_friend/automations/implements/tornado.py
Labels: enhancement

#142 Use latest detector
  docker-compose.jetson.orin.yml
Labels: enhancement

#143 Punch demo
  field_friend/automations/implements/tornado.py
  field_friend/automations/puncher.py
  field_friend/hardware/tornado.py
Labels: enhancement

#103 Fixing Follow Crop Navigation
  backup/rb34/field_friend.automations.implements.weeding_screw.json
  backup/rb34/field_friend.automations.plant_locator.json
  backup/rb34/field_friend.automations.plant_provider.json
  tests/test_navigation.py
Labels: enhancement

#128 Driving timeout
  field_friend/automations/automation_watcher.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  tests/test_navigation.py
Labels: bug
