Repository zauberzeug/field_friend, pull requests merged in 2024-05, with the labels that each got.

#44 Fix random shutdowns produced by GNSS signal data
  field_friend/navigation/gnss.py
Labels: bug

#43 Correctly await `can_start` handler in automation controls
  field_friend/interface/components/automation_controls.py
Labels: bug

#42 Provide map buttons to center on robot and toggle basemap
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/pages/field_planner_page.py
  field_friend/interface/pages/main_page.py
Labels: enhancement

#39 Remove non-functional restart via keyboard shortcut
  field_friend/interface/components/key_controls.py
Labels: enhancement

#34 General code review
  field_friend/automations/automation_watcher.py
  field_friend/automations/plant_locator.py
  field_friend/interface/components/monitoring.py
  field_friend/interface/components/robot_scene.py
  field_friend/interface/pages/monitor_page.py
  field_friend/system.py
  field_friend/vision/camera_configurator.py
  main.py
Labels: enhancement

#33 More compact routes documentation
  main.py
Labels: documentation

#40 formatting of operation.py
  field_friend/interface/components/operation.py
Labels: enhancement

#32 Provide MkDocs infrastructure
  .github/workflows/publish.yml
  .gitignore
  CODE_OF_CONDUCT.md
  README.md
  docs/contributing.md
  docs/features/field_planner.md
  docs/features/user_interface.md
  docs/generate_reference.py
  docs/getting_started.md
  docs/index.md
  docs/stylesheets/extra.css
  docs/troubleshooting.md
  field_friend/automations/__init__.py
  mkdocs.yml
  mkdocs_requirements.txt
Labels: documentation

#51 implement persistence_key to distinguish between weeding automation
  field_friend/automations/plant_locator.py
  field_friend/automations/weeding.py
  field_friend/interface/components/operation.py
  field_friend/system.py
Labels: bug

#47 Put "zoom to field" into the map's button bar
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/components/operation.py
Labels: enhancement

#49 Persist current automation via RoSys, not app.user
  field_friend/interface/components/operation.py
  field_friend/system.py
Labels: bug

#48 Fix, improve and simplify field selection
  field_friend/automations/field_provider.py
  field_friend/interface/components/operation.py
Labels: bug, enhancement

#57 Punch interface
  field_friend/automations/plant_locator.py
  field_friend/automations/plant_provider.py
  field_friend/automations/puncher.py
  field_friend/automations/weeding.py
  field_friend/interface/components/operation.py
  field_friend/interface/components/punch_dialog.py
Labels: enhancement

#50 Introduce pytest infrastructure and demonstrate usage with simple gnss test
  pytest.ini
  tests/conftest.py
  tests/test_gnss.py
Labels: enhancement

#64 Make plant positioning more robust
  field_friend/automations/plant_provider.py
  field_friend/automations/weeding.py
  field_friend/interface/components/punch_dialog.py
Labels: enhancement

#52 Ensure GNSS failures really stop the robot in all cases
  field_friend.automations.field_provider.json
  field_friend/automations/automation_watcher.py
  field_friend/automations/coverage_planer.py
  field_friend/automations/field_provider.py
  field_friend/automations/mowing.py
  field_friend/automations/path_provider.py
  field_friend/automations/path_recorder.py
  field_friend/automations/weeding.py
  field_friend/interface/components/field_object.py
  field_friend/interface/components/field_planner.py
  field_friend/interface/components/geodata_picker.py
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/components/operation.py
  field_friend/interface/components/path_planner.py
  field_friend/interface/components/status_dev.py
  field_friend/interface/components/status_drawer.py
  field_friend/navigation/__init__.py
  field_friend/navigation/geo_point.py
  field_friend/navigation/gnss.py
  field_friend/navigation/gnss_hardware.py
  field_friend/navigation/gnss_simulation.py
  field_friend/navigation/point_transformation.py
  field_friend/system.py
  field_friend/vision/camera_configurator.py
  requirements.txt
  tests/conftest.py
  tests/old_field_provider_persistence.json
  tests/test_field_provider.py
  tests/test_gnss.py
Labels: enhancement
