Repository zauberzeug/field_friend, pull requests merged in 2025-06, with the labels that each got.

#335 Switch motor directions for U6
  config/u6.py
Labels: bug

#283 Improve navigating to target and Tornado implement handling
  config/u4.py
  field_friend/automations/automation_watcher.py
  field_friend/automations/implements/implement.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/crossglide_demo_navigation.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/automations/plant_locator.py
  field_friend/automations/puncher.py
  field_friend/hardware/__init__.py
  field_friend/hardware/double_wheels.py
  field_friend/hardware/field_friend_simulation.py
  field_friend/hardware/y_axis_stepper_hardware.py
  field_friend/interface/components/hardware_control.py
  field_friend/robot_locator.py
  field_friend/system.py
  field_friend/vision/calibratable_usb_camera.py
  field_friend/vision/calibratable_usb_camera_provider.py
  requirements.txt
  tests/conftest.py
  tests/test_navigation.py
  tests/test_weeding.py
Labels: enhancement

#336 Manually use garbage collection
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/system.py
  requirements.txt
Labels: enhancement

#341 Set the robot's id as detector source
  field_friend/automations/plant_locator.py
  main.py
Labels: enhancement

#344 Fix bed name removal from `FieldObject`
  field_friend/interface/components/field_object.py
Labels: bug

#347 Formatting and cosmetical changes for the navigation code
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  tests/test_field_provider.py
  tests/test_navigation.py
Labels: enhancement

#346 Ensure environment variables are loaded from the .env file
  main.py
Labels: enhancement

#311 Change `safety.py` to use lizard PR 139
  field_friend/hardware/safety.py
Labels: enhancement, breaking change

#350 Add basic set of cursor rules
  .cursor/rules/coding.mdc
  .cursor/rules/general.mdc
  CONTRIBUTING.md
Labels: enhancement

#353 Update RoSys, implement the driver's minimum speed limit and remove persistence workaround
  config/f20.py
  field_friend/system.py
  requirements.txt
  tests/conftest.py
  tests/test_navigation.py
Labels: enhancement

#342 Improve Tornado weeding workflow
  field_friend/automations/implements/tornado.py
  field_friend/automations/puncher.py
  field_friend/hardware/tornado.py
  tests/test_weeding.py
Labels: enhancement
