Repository zauberzeug/field_friend, pull requests merged in 2025-01, with the labels that each got.

#252 add f10 config
  config/ff10XL_config_rb30/hardware.py
  config/ff10XL_config_rb30/params.py
  config/ff10XL_config_rb30/robotbrain.py
Labels: bug

#249 Setup F19
  backup/rb48/field_friend.automations.field_provider.json
  backup/rb48/field_friend.automations.implements.weeding_screw.json
  backup/rb48/field_friend.automations.kpi_provider.json
  backup/rb48/field_friend.automations.navigation.crossglide_demo_navigation.json
  backup/rb48/field_friend.automations.navigation.field_navigation.json
  backup/rb48/field_friend.automations.navigation.follow_crops_navigation.json
  backup/rb48/field_friend.automations.navigation.straight_line_navigation.json
  backup/rb48/field_friend.automations.path_provider.json
  backup/rb48/field_friend.automations.plant_locator.json
  backup/rb48/field_friend.automations.plant_provider.json
  backup/rb48/field_friend.localization.gnss_hardware.json
  backup/rb48/field_friend.system.json
  backup/rb48/field_friend.vision.calibratable_usb_camera_provider.json
  backup/rb48/rosys.config.json
  backup/rb48/rosys.vision.mjpeg_camera.mjpeg_camera_provider.json
  config/f19_config_rb48/camera.py
  config/f19_config_rb48/hardware.py
  config/f19_config_rb48/params.py
  config/f19_config_rb48/robotbrain.py
Labels: enhancement

#251 add @track to the automations and navigations
  field_friend/automations/implements/implement.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/automations/puncher.py
  field_friend/interface/dev_page.py
Labels: enhancement

#231 Rosys GNSS + Kalman Filter
  Dockerfile
  field_friend/automations/automation_watcher.py
  field_friend/automations/field.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/follow_crops_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/automations/plant_locator.py
  field_friend/interface/components/calibration_dialog.py
  field_friend/interface/components/camera_card.py
  field_friend/interface/components/development.py
  field_friend/interface/components/field_creator.py
  field_friend/interface/components/field_friend_object.py
  field_friend/interface/components/field_object.py
  field_friend/interface/components/geodata_importer.py
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/components/robot_scene.py
  field_friend/interface/components/status_dev.py
  field_friend/interface/components/status_drawer.py
  field_friend/interface/components/support_point_dialog.py
  field_friend/interface/main_page.py
  field_friend/localization/__init__.py
  field_friend/localization/geo_point.py
  field_friend/localization/gnss.py
  field_friend/localization/gnss_hardware.py
  field_friend/localization/gnss_simulation.py
  field_friend/log_configuration.py
  field_friend/robot_locator.py
  field_friend/system.py
  field_friend/vision/camera_configurator.py
  requirements.txt
  tests/conftest.py
  tests/old_field_provider_persistence.json
  tests/test_field_creator.py
  tests/test_field_provider.py
  tests/test_geo.py
  tests/test_gnss.py
  tests/test_navigation.py
  tests/test_weeding.py
Labels: enhancement

#256 Rename F14 and F15 Config
  config/f14_config_rb37/camera.py
  config/f14_config_rb37/hardware.py
  config/f14_config_rb37/params.py
  config/f14_config_rb37/robotbrain.py
  config/f15_config_rb39/camera.py
  config/f15_config_rb39/hardware.py
  config/f15_config_rb39/params.py
  config/f15_config_rb39/robotbrain.py
Labels: enhancement

#257 Remove old Camera Config
  field_friend/vision/__init__.py
  field_friend/vision/camera_configurations.py
Labels: enhancement

#250 Swarm Dashboard Connection
  field_friend/system.py
  main.py
  tests/conftest.py
Labels: enhancement

#262 change detector watchdog to debug log
  field_friend/automations/plant_locator.py
Labels: enhancement

#245 Remove quickfix for Lizard issue 66
  field_friend/hardware/status_control.py
  field_friend/hardware/tornado.py
  field_friend/hardware/y_axis_canopen_hardware.py
  field_friend/hardware/y_axis_stepper_hardware.py
  field_friend/hardware/z_axis_canopen_hardware.py
  field_friend/hardware/z_axis_stepper_hardware.py
  requirements.txt
Labels: enhancement

#265 Set default system variable values
  field_friend/interface/components/operation.py
  field_friend/system.py
Labels: bug

#266 Update to RoSys 0.22.1 to fix GNSS error #264
  requirements.txt
Labels: bug

#253 Add log view
  field_friend/automations/automation_watcher.py
  field_friend/automations/implements/external_mower.py
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/implements/weeding_screw.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/navigation/straight_line_navigation.py
  field_friend/automations/plant_locator.py
  field_friend/automations/plant_provider.py
  field_friend/automations/puncher.py
  field_friend/hardware/double_wheels.py
  field_friend/hardware/external_mower.py
  field_friend/hardware/field_friend.py
  field_friend/hardware/field_friend_hardware.py
  field_friend/hardware/flashlight.py
  field_friend/hardware/safety.py
  field_friend/hardware/tornado.py
  field_friend/hardware/y_axis_canopen_hardware.py
  field_friend/hardware/z_axis_canopen_hardware.py
  field_friend/hardware/z_axis_stepper_hardware.py
  field_friend/interface/components/__init__.py
  field_friend/interface/components/development.py
  field_friend/interface/components/geodata_importer.py
  field_friend/interface/components/key_controls.py
  field_friend/interface/components/log_monitor.py
  field_friend/interface/dev_page.py
  field_friend/log_configuration.py
  field_friend/system.py
  field_friend/vision/camera_configurator.py
  main.py
Labels: enhancement

#263 Add status API endpoints
  field_friend/api/__init__.py
  field_friend/api/online.py
  field_friend/api/status.py
  field_friend/system.py
  main.py
Labels: enhancement

#272 Update detector to version 0.1.10-nlv0.13.4
  docker-compose.jetson.orin.yml
Labels: duplicate

#274 Fixing missing bed_crops backup bug
  field_friend/automations/field.py
Labels: bug

#275 Add a minimal lizard script for ODrive calibration
  odrive/calibration.liz
Labels: enhancement

#273 Move GNSS distance to reference check to field navigation
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
Labels: enhancement
