Repository zauberzeug/field_friend, pull requests merged in 2025-04, with the labels that each got.

#304 Split up code checker jobs to run them separately
  .github/workflows/test.yml
Labels: enhancement

#303 Update to RoSys 0.23.0
  field_friend/automations/field_provider.py
  field_friend/automations/path_provider.py
  field_friend/automations/plant_provider.py
  field_friend/hardware/teltonika_router.py
  field_friend/interface/components/header_bar.py
  field_friend/interface/components/log_monitor.py
  field_friend/system.py
  requirements.txt
Labels: enhancement

#306 Save GeoReference heading in persistence
  field_friend/system.py
Labels: enhancement

#310 Make gnss optional and avoid numerical instabilities in simulation
  field_friend/api/automation.py
  field_friend/api/status.py
  field_friend/automations/automation_watcher.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/navigation/field_navigation.py
  field_friend/automations/navigation/navigation.py
  field_friend/automations/plant_locator.py
  field_friend/interface/components/field_creator.py
  field_friend/interface/components/leaflet_map.py
  field_friend/interface/components/support_point_dialog.py
  field_friend/interface/dev_page.py
  field_friend/robot_locator.py
  field_friend/system.py
Labels: bug

#312 Handle missing camera config
  backup/rb34/field_friend.automations.field_provider.json
  backup/rb34/field_friend.automations.implements.weeding_screw.json
  backup/rb34/field_friend.automations.kpi_provider.json
  backup/rb34/field_friend.automations.navigation.field_navigation.json
  backup/rb34/field_friend.automations.navigation.follow_crops_navigation.json
  backup/rb34/field_friend.automations.navigation.row_on_field_navigation.json
  backup/rb34/field_friend.automations.navigation.straight_line_navigation.json
  backup/rb34/field_friend.automations.plant_locator.json
  backup/rb34/field_friend.automations.plant_provider.json
  backup/rb34/field_friend.interface.components.log_monitor.json
  backup/rb34/field_friend.robot_locator.json
  backup/rb34/field_friend.system.json
  backup/rb34/field_friend.vision.calibratable_usb_camera_provider.json
  backup/rb34/rosys.vision.mjpeg_camera.mjpeg_camera_provider.json
  field_friend/automations/implements/weeding_implement.py
  field_friend/automations/plant_locator.py
  field_friend/interface/components/camera_card.py
  field_friend/interface/components/field_friend_object.py
  field_friend/interface/components/monitoring.py
  field_friend/interface/main_page.py
  field_friend/system.py
  field_friend/vision/camera_configurator.py
Labels: bug, enhancement

#313 Add low bandwidth page
  field_friend/interface/__init__.py
  field_friend/interface/components/header_bar.py
  field_friend/interface/low_bandwidth_page.py
  field_friend/interface/main_page.py
  main.py
Labels: enhancement

#314 Improve debugging visibility with a lighter image overlay
  field_friend/automations/implements/tornado.py
  field_friend/automations/implements/weeding_implement.py
  field_friend/interface/components/camera_card.py
Labels: enhancement

#309 Setup F22
  config/f22.py
  field_friend/interface/__init__.py
Labels: enhancement

#316 Allow robots without implement and camera
  config/u5.py
  field_friend/automations/implements/implement.py
  field_friend/config/configuration.py
  field_friend/system.py
Labels: enhancement
